name: Build

concurrency:
    group: build-${{ github.head_ref }}
    cancel-in-progress: true

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
    workflow_dispatch:

jobs:
    # Build job for Windows
    build-windows:
        strategy:
            fail-fast: false
            matrix:
                include:
                    - name: Windows Server 2019 MinGW
                      image: windows-2019
                      shell: msys2 {0}
                      build-type: Debug
                      qt-arch: "win32_mingw81"
                      experimental: false
        name: ${{ matrix.name }} ${{ matrix.build-type }}
        runs-on: ${{ matrix.image }}
        continue-on-error: ${{ matrix.experimental }}
        defaults:
            run:
                shell:  ${{ matrix.shell }}

        steps:
            - uses: actions/checkout@v3

            - name: Install Dependencies (msys2)
              if: startsWith(matrix.shell, 'msys2')
              uses: msys2/setup-msys2@v2
              with:
                  install: >-
                      mingw-w64-i686-toolchain
                      mingw-w64-i686-ninja
                  msystem: mingw32
                  release: false
            #mingw-w64-x86_64-SDL2 not installed above because of: https://github.com/AntiMicroX/antimicrox/issues/465
            - name: Install sdl2 (mingw-w32)
              if: startsWith(matrix.shell, 'msys2')
              run: |
                curl -L -o mingw-w64-i686-SDL2-2.0.20-1-any.pkg.tar.zst https://mirror.msys2.org/mingw/mingw32/mingw-w64-i686-SDL2-2.0.20-1-any.pkg.tar.zst
                pacman --noconfirm -U mingw-w64-i686-SDL2-2.0.20-1-any.pkg.tar.zst

            - name: Install Qt
              uses: jurplel/install-qt-action@v2
              with:
                  version: "5.15.2"
                  host: "windows"
                  target: "desktop"
                  arch: ${{ matrix.qt-arch }}
                  dir: "${{ github.workspace }}/qt/"
                  install-deps: "true"
              
            - name: Configure CMake
              run: cmake -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -B "${{ github.workspace }}/build" ${{ matrix.cmake-args }}
              env:
                  CMAKE_PREFIX_PATH: ${{ env.Qt5_Dir }}
                  WORKSPACE_DIR: ${{ github.workspace }}
              
            - name: Build
              run: cmake --build "${{ github.workspace }}/build" --parallel 8
